#!/usr/bin/env bash
set -eu
root="$(cd "$(dirname "$0")/.." && pwd)"; . "$root/scripts/lib/provider-dispatch.sh"
fail() { echo "FAIL: $*" >&2; exit 1; }
join() { printf '<%s>' "$@"; }
mana_provider_profile_args codex '/repo path' model 3 1; [ "$(join "${MANA_PROVIDER_ARGS[@]}")" = '<--ask-for-approval><on-request><exec><--model><model><--cd></repo path><--sandbox><workspace-write><-c><agents.max_threads=3><-c><agents.max_depth=1><-c><agents.interrupt_message=false>' ] || fail 'Codex profile args changed'
mana_provider_profile_args claude '/repo path' model 3 1; [ "$(join "${MANA_PROVIDER_ARGS[@]}")" = '<-p><--agent><mana-orchestrator><--model><model><--permission-mode><default>' ] || fail 'Claude profile args changed'
mana_provider_profile_args opencode '/repo path' model 3 1; [ "$(join "${MANA_PROVIDER_ARGS[@]}")" = '<run><--dir></repo path><--model><model><--agent><mana_orchestrator>' ] || fail 'OpenCode profile args changed'
mana_provider_repair_args codex '/repo path' model; [ "$(join "${MANA_PROVIDER_ARGS[@]}")" = '<--ask-for-approval><never><exec><--model><model><--cd></repo path><--sandbox><workspace-write><--ephemeral><--ignore-user-config><--disable><multi_agent><--disable><multi_agent_v2><-c><agents.max_threads=1><-c><agents.max_depth=0><-c><agents.interrupt_message=false>' ] || fail 'Codex repair containment args incorrect'
printf '%s\n' "${MANA_PROVIDER_ARGS[@]}" | grep -Fxq 'agents.max_depth=0' || fail 'repair subagents not disabled'
mana_provider_synthesis_args codex '/empty workspace' model; [ "$(join "${MANA_PROVIDER_ARGS[@]}")" = '<--ask-for-approval><never><exec><--model><model><--cd></empty workspace><--sandbox><read-only><--ephemeral><--ignore-user-config><--disable><multi_agent><--disable><multi_agent_v2><-c><agents.max_threads=1><-c><agents.max_depth=0><-c><agents.interrupt_message=false>' ] || fail 'Codex synthesis args incorrect'
printf '%s\n' "${MANA_PROVIDER_ARGS[@]}" | grep -Fxq 'agents.max_depth=0' || fail 'synthesis subagents not disabled'
mana_provider_synthesis_args codex '/mana-created/scratch' model host-disposable-non-git; [ "$(join "${MANA_PROVIDER_ARGS[@]}")" = '<--ask-for-approval><never><exec><--skip-git-repo-check><--model><model><--cd></mana-created/scratch><--sandbox><read-only><--ephemeral><--ignore-user-config><--disable><multi_agent><--disable><multi_agent_v2><-c><agents.max_threads=1><-c><agents.max_depth=0><-c><agents.interrupt_message=false>' ] || fail 'disposable_non_git_codex_exec_skips_repo_check'
mana_provider_synthesis_args codex '/mana-created/scratch' model host-disposable-non-git '/host/m3-flat.schema.json'; [ "$(join "${MANA_PROVIDER_ARGS[@]}")" = '<--ask-for-approval><never><exec><--skip-git-repo-check><--output-schema></host/m3-flat.schema.json><--model><model><--cd></mana-created/scratch><--sandbox><read-only><--ephemeral><--ignore-user-config><--disable><multi_agent><--disable><multi_agent_v2><-c><agents.max_threads=1><-c><agents.max_depth=0><-c><agents.interrupt_message=false>' ] || fail 'Codex synthesis structured-output args incorrect'
mana_provider_synthesis_args codex '/mana-created/scratch' model host-disposable-non-git '/host/m3-flat.schema.json' high; [ "$(join "${MANA_PROVIDER_ARGS[@]}")" = '<--ask-for-approval><never><exec><--skip-git-repo-check><--output-schema></host/m3-flat.schema.json><--model><model><--cd></mana-created/scratch><--sandbox><read-only><--ephemeral><--ignore-user-config><-c><model_reasoning_effort="high"><--disable><multi_agent><--disable><multi_agent_v2><-c><agents.max_threads=1><-c><agents.max_depth=0><-c><agents.interrupt_message=false>' ] || fail 'Codex synthesis reasoning effort did not follow ignore-user-config'
mana_provider_synthesis_args codex '/mana-created/scratch' model host-disposable-non-git '' extreme && fail 'unsupported Codex synthesis reasoning effort was accepted'
mana_provider_synthesis_args codex '/ordinary/repository' model; printf '%s\n' "${MANA_PROVIDER_ARGS[@]}" | grep -Fxq -- '--skip-git-repo-check' && fail 'normal_repo_codex_exec_keeps_repo_check'
mana_provider_synthesis_args codex '/arbitrary/non-git' model; printf '%s\n' "${MANA_PROVIDER_ARGS[@]}" | grep -Fxq -- '--skip-git-repo-check' && fail 'arbitrary_non_git_workspace_does_not_implicitly_bypass_check'
mana_provider_synthesis_args codex '/arbitrary/non-git' model untrusted-contract && fail 'unknown synthesis workspace contract was accepted'
echo 'Provider dispatch tests passed'
