#!/usr/bin/env bash
set -eu

root="${1:-$(cd "$(dirname "$0")/.." && pwd)}"

field() {
  awk -v key="$2" '
    $0 == "---" { delimiters++; next }
    delimiters == 2 { exit }
    delimiters == 1 && index($0, key ":") == 1 {
      value = substr($0, length(key) + 2)
      sub(/^[[:space:]]+/, "", value)
      gsub(/^\"|\"$/, "", value)
      print value
      exit
    }
  ' "$1"
}

printf '%s\n' '# Generated by scripts/build-skill-index.sh. Do not edit manually.'
printf '%s\n' 'version: 1'
printf '%s\n' 'skills:'

for skill in "$root"/skills/*/SKILL.md; do
  [ -f "$skill" ] || continue
  id="$(field "$skill" name)"
  risk="$(field "$skill" risk_level)"
  tier="$(field "$skill" model_tier)"
  mode="$(field "$skill" execution_mode)"
  group="$(field "$skill" delegation_group)"
  relative_path="${skill#"$root"/}"

  printf '  - id: %s\n' "$id"
  printf '    path: %s\n' "$relative_path"
  printf '    risk_level: %s\n' "${risk:-unspecified}"
  printf '    model_tier: %s\n' "${tier:-unspecified}"
  printf '    execution_mode: %s\n' "${mode:-unspecified}"
  printf '    delegation_group: %s\n' "${group:-unspecified}"
done
