#!/usr/bin/env bash
# Repository-local governance metrics. Inventory and actual eval coverage stay separate.
set -eu
root="$(cd "$(dirname "$0")/.." && pwd)"; project_root="$(pwd)"; json=false
. "$root/scripts/lib/json.sh"; . "$root/scripts/lib/run-identity.sh"; . "$root/scripts/lib/profile-metadata.sh"
while [ "$#" -gt 0 ]; do case "$1" in --project-root) project_root="${2:-}"; shift 2;; --json) json=true; shift;; --help|-h) echo 'Usage: mana report governance [--json]'; exit 0;; *) echo "ERROR: unknown option: $1" >&2; exit 2;; esac; done
project_root="$(cd "$project_root" && pwd)"; mana_json_require
profiles="$(find "$root/profiles" -name '*.yaml' -type f | wc -l | tr -d ' ')"; skills="$(awk '/^  - id:/{n++} END{print n+0}' "$root/skills/index.yaml")"; gates="$(grep -l '^human_approval_requirement: true' "$root"/profiles/*.yaml | wc -l | tr -d ' ')"
risk_levels="$(awk '/^    risk_level:/{print $2}' "$root/skills/index.yaml" | LC_ALL=C sort -u | tr '\n' ' ')"; tiers="$(awk '/^    model_tier:/{print $2}' "$root/skills/index.yaml" | LC_ALL=C sort -u | tr '\n' ' ')"
latest_files="$(find "$project_root/.mana/evaluations/results" -name latest.json -type f 2>/dev/null | LC_ALL=C sort)"; total=0; passed=0; exercised_profiles=""; exercised_skills=""; gate_assert_profiles=""; eval_risks=""; eval_tiers=""; stale=0
while IFS= read -r f; do [ -n "$f" ] || continue; total=$((total+1)); jq -e '.pass == true' "$f" >/dev/null && passed=$((passed+1)); p="$(jq -r .profile "$f")"; exercised_profiles="${exercised_profiles}${exercised_profiles:+$'\n'}$p"; jq -r '.selectedSkills[]?' "$f" | while IFS= read -r s; do echo "$s"; done >> "${TMPDIR:-/tmp}/mana-governance-skills-$$"; jq -e '.assertions[]? | select(.type == "must_require_gate")' "$f" >/dev/null && gate_assert_profiles="${gate_assert_profiles}${gate_assert_profiles:+$'\n'}$p"; while IFS= read -r s; do meta="$(awk -v id="$s" '$1=="-"&&$2=="id:"{a=($3==id)} a&&$1=="risk_level:"{r=$2} a&&$1=="model_tier:"{t=$2} END{print r "|" t}' "$root/skills/index.yaml")"; eval_risks="${eval_risks}${eval_risks:+$'\n'}${meta%%|*}"; eval_tiers="${eval_tiers}${eval_tiers:+$'\n'}${meta#*|}"; done < <(jq -r '.selectedSkills[]?' "$f"); current_profile="$root/profiles/$p.yaml"; [ -f "$current_profile" ] && [ "$(jq -r .profileDigest "$f")" = "$(mana_digest_file "$current_profile")" ] && [ "$(jq -r .skillIndexDigest "$f")" = "$(mana_digest_file "$root/skills/index.yaml")" ] || stale=$((stale+1)); done <<EOF
$latest_files
EOF
skill_exercised=0; [ -f "${TMPDIR:-/tmp}/mana-governance-skills-$$" ] && skill_exercised="$(LC_ALL=C sort -u "${TMPDIR:-/tmp}/mana-governance-skills-$$" | sed '/^$/d' | wc -l | tr -d ' ')"; rm -f "${TMPDIR:-/tmp}/mana-governance-skills-$$"
profile_exercised="$(printf '%s\n' "$exercised_profiles" | sed '/^$/d' | LC_ALL=C sort -u | wc -l | tr -d ' ')"; gate_exercised="$(printf '%s\n' "$gate_assert_profiles" | sed '/^$/d' | LC_ALL=C sort -u | wc -l | tr -d ' ')"; risk_exercised="$(printf '%s\n' "$eval_risks" | sed '/^$/d' | LC_ALL=C sort -u | wc -l | tr -d ' ')"; tier_exercised="$(printf '%s\n' "$eval_tiers" | sed '/^$/d' | LC_ALL=C sort -u | wc -l | tr -d ' ')"; risk_total="$(printf '%s\n' "$risk_levels" | tr ' ' '\n' | sed '/^$/d' | wc -l | tr -d ' ')"; tier_total="$(printf '%s\n' "$tiers" | tr ' ' '\n' | sed '/^$/d' | wc -l | tr -d ' ')"
candidate_counts="$(find "$project_root/.mana/learning/candidates" -name '*.json' -type f 2>/dev/null | while IFS= read -r f; do jq -r .status "$f"; done | LC_ALL=C sort | uniq -c | awk '{print $2 "=" $1}')"
run_id="$(mana_run_id)"; generated="$(mana_generated_at)"; project_rev="$(mana_project_revision "$project_root")"; outdir="$project_root/.mana/reports/governance/$project_rev"; mkdir -p "$outdir"; out="$outdir/$run_id.md"
{ echo '# Mana Governance Report'; echo; echo "Run: \`$run_id\`"; echo; echo '| Inventory / metric | Value |'; echo '|---|---:|'; echo "| Profile inventory | $profiles |"; echo "| Indexed skills | $skills |"; echo "| Declared risk levels | $risk_levels |"; echo "| Profiles requiring human approval | $gates |"; echo "| Declared model tiers | $tiers |"; echo "| Profile eval coverage | $profile_exercised / $profiles |"; echo "| Skill eval coverage | $skill_exercised / $skills |"; echo "| Human-gate eval coverage | $gate_exercised / $gates |"; echo "| Risk-level eval coverage | $risk_exercised / $risk_total |"; echo "| Model-tier eval coverage | $tier_exercised / $tier_total |"; echo "| Current eval pass rate | $passed / $total |"; echo "| Stale result count | $stale |"; echo "| Learning candidates | ${candidate_counts:-none} |"; echo; echo '## Scope'; echo; echo 'Structural coverage does not prove semantic model quality. A passing fixture-backed assertion does not prove autonomous detection. An evaluated profile is not necessarily production-safe. Human approval remains outside automatic evaluation. Use `mana eval compare` with explicit result paths for regression review.'; } > "$out"
cp "$out" "$outdir/latest.md"
if [ "$json" = true ]; then jq -cn --arg report "$out" --arg run "$run_id" --arg generated "$generated" --arg rev "$project_rev" --argjson profiles "$profiles" --argjson skills "$skills" --argjson stale "$stale" --argjson total "$total" --argjson passed "$passed" '{schemaVersion:"2",report:$report,runId:$run,generatedAt:$generated,projectRevision:$rev,profiles:$profiles,indexedSkills:$skills,staleResultCount:$stale,currentEvalPassRate:{passed:$passed,total:$total},repositoryModified:false,manaStateWritten:true,telemetryWritten:false,runnerInvoked:false,externalToolInvoked:false}'; else echo 'MANA GOVERNANCE REPORT'; echo "$out"; fi
