#!/usr/bin/env bash
# Append-only Journey Model v0. Records are JSON documents stored with a .yaml
# extension: JSON is valid YAML and keeps the v0 runtime dependency-free.
set -eu

root="$(cd "$(dirname "$0")/.." && pwd)"
project_root="$(pwd)"
json=false

usage() {
  cat <<'USAGE' >&2
Usage: mana journey <command> [options]

Commands:
  create --title <text> --start-kind <kind> --start-value <value> \
         --termination-kind <kind> --termination-condition <condition>
  add-node <journey-id> --kind <kind> [--state discovered|expanded] [--label <text>] [--disposition primary|deferred]
  add-edge <journey-id> --from <node-id> --to <node-id> --kind <relation> [--disposition primary|deferred]
  add-anchor <journey-id> --node <node-id> --revision <revision> --path <path> \
             --start-line <n> --end-line <n> [--symbol <symbol>] [--fingerprint <value>]
  add-evidence <journey-id> --kind <kind> [--anchor <anchor-id>] [--summary <text>]
  add-explanation <journey-id> --subject <node-id> [--evidence <id> ...] [--status <status>]
                  [--body <text>] [--epistemic-status <status>]
  add-enrichment <journey-id> --request-id <exr-id> --subject <node-id> \
                 --kind explanation --status requested|completed|failed [--reason <text>]
  add-hypothesis <journey-id> --subject <node-id> --claim <text> \
             [--confidence <state>] [--supports <evidence-id> ...] [--contradicts <evidence-id> ...]
  add-concept-occurrence <journey-id> --concept-id <cpt_id> --subject <node-id> \
             [--relevance primary|supporting|incidental] [--evidence <id> ...]
  add-traversal <journey-id> --kind <kind> --entry <node-id> [--nodes <node-id> ...]
  add-cycle-region <journey-id> --entry <node-id> --kind <kind> --nodes <node-id> ... \
             --back-edge <edge-id> [--back-edge <edge-id> ...]
  validate <journey-id>
  materialize <journey-id> [--json]

Journey data is stored at .mana/learning/journeys/<journey-id>/.
All IDs are generated by this host; callers cannot supply record IDs.
USAGE
}

fail() { echo "ERROR: $*" >&2; exit 2; }
need() { [ -n "${2:-}" ] || fail "$1 requires a value"; }
journey_id_ok() { printf '%s' "$1" | grep -Eq '^jrn_[a-f0-9]{24}$'; }
record_id_ok() { printf '%s' "$1" | grep -Eq '^(jn|je|anc|ev|exp|hyp|occ|trv|cyc|enr)_[a-f0-9]{24}$'; }
concept_id_ok() { awk -F '\t' -v id="$1" 'NR > 1 && $1 == id { found=1 } END { exit !found }' "$root/learning-kb/concept-index.tsv" 2>/dev/null; }
journeys_dir() { printf '%s/.mana/learning/journeys' "$project_root"; }
journey_dir() { printf '%s/%s' "$(journeys_dir)" "$1"; }
meta_file() { printf '%s/journey.yaml' "$(journey_dir "$1")"; }
records_dir() { printf '%s/records' "$(journey_dir "$1")"; }
require_journey() { journey_id_ok "$1" || fail "invalid journey id: $1"; [ -f "$(meta_file "$1")" ] || fail "journey not found: $1"; }

new_id() {
  local prefix="$1" candidate
  while :; do
    candidate="${prefix}_$(LC_ALL=C tr -dc 'a-f0-9' < /dev/urandom | head -c 24)"
    [ "${#candidate}" -eq $(( ${#prefix} + 25 )) ] || continue
    if ! find "$(journeys_dir)" -type f -name '*.yaml' -exec grep -Fql "\"id\":\"$candidate\"" {} + 2>/dev/null; then
      printf '%s' "$candidate"; return
    fi
  done
}

append_record() {
  local journey="$1" type="$2" id="$3" payload="$4" file
  file="$(records_dir "$journey")/${id}-${type}.yaml"
  [ ! -e "$file" ] || fail "record collision: $id"
  umask 077
  printf '%s\n' "$payload" > "$file"
}

exists_id() {
  local journey="$1" id="$2"
  [ "$id" = "$(jq -r '.id' "$(meta_file "$journey")")" ] && return 0
  find "$(records_dir "$journey")" -type f -name '*.yaml' -exec jq -e --arg id "$id" 'select(.id == $id)' {} \; >/dev/null 2>&1
}
validation_inventory=""
record_kind() {
  if [ -n "$validation_inventory" ]; then
    awk -F '\t' -v id="$2" '$1 == id { print $2; exit }' "$validation_inventory"
    return
  fi
  find "$(records_dir "$1")" -type f -name '*.yaml' -exec jq -r --arg id "$2" 'select(.id == $id) | .record_type' {} \; 2>/dev/null | head -n 1
}
require_id_kind() {
  if [ -n "$validation_inventory" ]; then
    [ "$(record_kind "$1" "$2")" = "$3" ] && return 0
    return 1
  fi
  exists_id "$1" "$2" || fail "unknown record id: $2"
  [ "$(record_kind "$1" "$2")" = "$3" ] || fail "$2 is not a $3"
}
array_json() { jq -Rsc 'split("\n") | map(select(length > 0))'; }

validate() {
  local journey="$1" errors file id type from to node anchor evidence subject inventory
  require_journey "$journey"; errors=0
  error() { echo "INVALID: $*" >&2; errors=1; }
  jq -e '(.schema == "mana.learning.journey/v1") and (.id|type == "string") and (.title|type == "string" and length > 0) and (.repository_revision|type == "string") and (.scope.start.kind|type == "string" and length > 0) and (.scope.start.value|type == "string" and length > 0) and (.scope.termination.kind|type == "string" and length > 0) and (.scope.termination.condition|type == "string" and length > 0)' "$(meta_file "$journey")" >/dev/null || error 'malformed journey metadata'
  inventory="$(mktemp "${TMPDIR:-/tmp}/mana-journey-inventory.XXXXXX")"
  validation_inventory="$inventory"
  jq -r '.id + "\tjourney"' "$(meta_file "$journey")" > "$inventory"
  while IFS= read -r file; do
    jq -r '.id + "\t" + .record_type' "$file" >> "$inventory" 2>/dev/null || true
  done < <(find "$(records_dir "$journey")" -type f -name '*.yaml' | LC_ALL=C sort)
  if [ "$(cut -f1 "$inventory" | LC_ALL=C sort | uniq -d | wc -l | tr -d ' ')" -ne 0 ]; then error 'duplicate record ID'; fi
  while IFS= read -r file; do
    jq -e '(.schema == "mana.learning.record/v1") and (.id|type == "string") and (.record_type|type == "string")' "$file" >/dev/null || { error "malformed record: ${file##*/}"; continue; }
    id="$(jq -r .id "$file")"; type="$(jq -r .record_type "$file")"
    record_id_ok "$id" || error "invalid host record id: $id"
    case "$type" in
      node) jq -e '(.kind|IN("code","runtime_effect","boundary","external_system","concept_occurrence","explanation","hypothesis","timeline_event")) and (.state|IN("discovered","expanded")) and ((.label? // "")|type == "string") and ((.disposition? // "primary")|IN("primary","deferred"))' "$file" >/dev/null || error "invalid node: $id" ;;
      edge) from="$(jq -r .from "$file")"; to="$(jq -r .to "$file")"; require_id_kind "$journey" "$from" node 2>/dev/null || error "edge $id has unknown from node: $from"; require_id_kind "$journey" "$to" node 2>/dev/null || error "edge $id has unknown to node: $to"; jq -e '(.kind|IN("CALLS","EXECUTES","DEPENDS_ON","RETURNS_TO","LOOP_BACK","EXPLAINS","EXEMPLIFIES","INTRODUCES_CONCEPT","DEEP_DIVE","MAY_EXIST_BECAUSE","SUPPORTED_BY","CONTRADICTED_BY","RELATED_TO")) and ((.disposition? // "primary")|IN("primary","deferred"))' "$file" >/dev/null || error "invalid edge kind: $id" ;;
      anchor) node="$(jq -r .node_id "$file")"; require_id_kind "$journey" "$node" node 2>/dev/null || error "anchor $id has unknown node: $node"; jq -e '(.revision|type == "string" and length > 0) and (.path|type == "string" and length > 0) and (.range.start_line|type == "number") and (.range.end_line|type == "number") and (.range.start_line >= 1) and (.range.end_line >= .range.start_line)' "$file" >/dev/null || error "invalid source anchor: $id" ;;
      evidence) anchor="$(jq -r '.anchor_id // empty' "$file")"; [ -z "$anchor" ] || require_id_kind "$journey" "$anchor" anchor 2>/dev/null || error "evidence $id has unknown anchor: $anchor"; jq -e '.kind|IN("source_range","symbol","configuration","test","git_commit","git_diff","documentation","adr","runtime_semantic")' "$file" >/dev/null || error "invalid evidence: $id" ;;
      explanation) subject="$(jq -r .subject_node_id "$file")"; require_id_kind "$journey" "$subject" node 2>/dev/null || error "explanation $id has unknown subject: $subject"; jq -e '((.status? // "available")|IN("available","completed","failed")) and ((.body? // "")|type == "string") and ((.epistemic_status? // "unknown")|IN("documented","strongly_supported","plausible","speculative","unknown"))' "$file" >/dev/null || error "invalid explanation: $id"; jq -r '.evidence_ids[]?' "$file" | while IFS= read -r evidence; do require_id_kind "$journey" "$evidence" evidence 2>/dev/null || { echo "INVALID: explanation $id has unknown evidence: $evidence" >&2; exit 1; }; done || errors=1 ;;
      enrichment) subject="$(jq -r .subject_node_id "$file")"; require_id_kind "$journey" "$subject" node 2>/dev/null || error "enrichment $id has unknown subject: $subject"; jq -e '(.request_id|type == "string" and test("^exr_[a-f0-9]{24}$")) and (.kind == "explanation") and (.status|IN("requested","completed","failed")) and ((.reason? // "")|type == "string")' "$file" >/dev/null || error "invalid enrichment: $id" ;;
      hypothesis) subject="$(jq -r .subject_node_id "$file")"; require_id_kind "$journey" "$subject" node 2>/dev/null || error "hypothesis $id has unknown subject: $subject"; jq -e '(.claim|type == "string" and length > 0) and (.confidence|IN("documented","strongly_supported","plausible","speculative","unknown"))' "$file" >/dev/null || error "invalid hypothesis: $id"; jq -r '(.supports[]?, .contradicts[]?)' "$file" | while IFS= read -r evidence; do require_id_kind "$journey" "$evidence" evidence 2>/dev/null || { echo "INVALID: hypothesis $id has unknown evidence: $evidence" >&2; exit 1; }; done || errors=1 ;;
      concept_occurrence) subject="$(jq -r .subject_node_id "$file")"; concept_id_ok "$(jq -r .concept_id "$file")" || error "invalid concept id: $id"; require_id_kind "$journey" "$subject" node 2>/dev/null || error "occurrence $id has unknown subject: $subject"; jq -r '.evidence_ids[]?' "$file" | while IFS= read -r evidence; do require_id_kind "$journey" "$evidence" evidence 2>/dev/null || { echo "INVALID: occurrence $id has unknown evidence: $evidence" >&2; exit 1; }; done || errors=1 ;;
      traversal) node="$(jq -r .entry_node_id "$file")"; require_id_kind "$journey" "$node" node 2>/dev/null || error "traversal $id has unknown entry: $node"; jq -r '.node_ids[]?' "$file" | while IFS= read -r node; do require_id_kind "$journey" "$node" node 2>/dev/null || { echo "INVALID: traversal $id has unknown node: $node" >&2; exit 1; }; done || errors=1 ;;
      cycle_region) node="$(jq -r .entry_node_id "$file")"; require_id_kind "$journey" "$node" node 2>/dev/null || error "cycle $id has unknown entry: $node"; jq -e '(.kind|IN("retry","polling","event_loop","state_cycle","recursive","unknown")) and (.node_ids as $nodes | ($nodes|type == "array" and length > 0) and (($nodes|unique|length) == ($nodes|length))) and (.back_edge_ids as $edges | ($edges|type == "array" and length > 0) and (($edges|unique|length) == ($edges|length))) and (.entry_node_id as $entry | .node_ids | index($entry) != null)' "$file" >/dev/null || error "invalid cycle region: $id"; jq -r '.node_ids[]?' "$file" | while IFS= read -r node; do require_id_kind "$journey" "$node" node 2>/dev/null || { echo "INVALID: cycle $id has unknown node: $node" >&2; exit 1; }; done || errors=1; jq -r '.back_edge_ids[]?' "$file" | while IFS= read -r evidence; do require_id_kind "$journey" "$evidence" edge 2>/dev/null || { echo "INVALID: cycle $id has unknown back edge: $evidence" >&2; exit 1; }; edge_file="$(records_dir "$journey")/${evidence}-edge.yaml"; [ -f "$edge_file" ] && jq -e --argjson nodes "$(jq -c .node_ids "$file")" '(.from as $from | .to as $to | (.kind == "LOOP_BACK") and ($nodes | index($from) != null) and ($nodes | index($to) != null))' "$edge_file" >/dev/null || { echo "INVALID: cycle $id has non-internal LOOP_BACK: $evidence" >&2; exit 1; }; done || errors=1 ;;
      *) error "unknown record type $type: $id" ;;
    esac
  done < <(find "$(records_dir "$journey")" -type f -name '*.yaml' | LC_ALL=C sort)
  rm -f "$inventory"; validation_inventory=""
  [ "$errors" -eq 0 ] || return 1
}

materialize() {
  local journey="$1" records
  validate "$journey" || fail "journey validation failed"
  records="$(find "$(records_dir "$journey")" -type f -name '*.yaml' | LC_ALL=C sort)"
  if [ -n "$records" ]; then
    jq -s --argjson journey "$(cat "$(meta_file "$journey")")" '{schema:"mana.learning.graph/v1",journey:$journey,nodes:(map(select(.record_type == "node"))|sort_by(.id)),edges:(map(select(.record_type == "edge"))|sort_by(.id)),anchors:(map(select(.record_type == "anchor"))|sort_by(.id)),evidence:(map(select(.record_type == "evidence"))|sort_by(.id)),explanations:(map(select(.record_type == "explanation"))|sort_by(.id)),enrichments:(map(select(.record_type == "enrichment"))|sort_by(.id)),hypotheses:(map(select(.record_type == "hypothesis"))|sort_by(.id)),concept_occurrences:(map(select(.record_type == "concept_occurrence"))|sort_by(.id)),traversals:(map(select(.record_type == "traversal"))|sort_by(.id)),cycle_regions:(map(select(.record_type == "cycle_region"))|sort_by(.id))}' $records
  else
    jq -n --argjson journey "$(cat "$(meta_file "$journey")")" '{schema:"mana.learning.graph/v1",journey:$journey,nodes:[],edges:[],anchors:[],evidence:[],explanations:[],enrichments:[],hypotheses:[],concept_occurrences:[],traversals:[],cycle_regions:[]}'
  fi
}

while [ "${1:-}" = "--project-root" ]; do project_root="${2:-}"; need --project-root "$project_root"; shift 2; done
command="${1:-}"; [ -n "$command" ] || { usage; exit 2; }; shift
case "$command" in
  --help|-h|help) usage; exit 0 ;;
  create)
    title=""; start_kind=""; start_value=""; termination_kind=""; termination_condition=""; revision="HEAD"
    while [ "$#" -gt 0 ]; do case "$1" in --title) title="${2:-}"; shift 2;; --start-kind) start_kind="${2:-}"; shift 2;; --start-value) start_value="${2:-}"; shift 2;; --termination-kind) termination_kind="${2:-}"; shift 2;; --termination-condition) termination_condition="${2:-}"; shift 2;; --revision) revision="${2:-}"; shift 2;; *) fail "unknown create option: $1";; esac; done
    for pair in "title:$title" "start-kind:$start_kind" "start-value:$start_value" "termination-kind:$termination_kind" "termination-condition:$termination_condition"; do [ -n "${pair#*:}" ] || fail "--${pair%%:*} is required"; done
    id="$(new_id jrn)"; mkdir -p "$(records_dir "$id")" "$(journey_dir "$id")/assets" "$(journey_dir "$id")/derived"; jq -cn --arg id "$id" --arg title "$title" --arg revision "$revision" --arg sk "$start_kind" --arg sv "$start_value" --arg tk "$termination_kind" --arg tc "$termination_condition" '{schema:"mana.learning.journey/v1",id:$id,title:$title,repository_revision:$revision,scope:{start:{kind:$sk,value:$sv},termination:{kind:$tk,condition:$tc},boundaries:{exclude:[]}}}' > "$(meta_file "$id")"; printf '%s\n' "$id" ;;
  add-node)
    journey="${1:-}"; shift || true; require_journey "$journey"; kind=""; state=discovered; label=""; disposition=primary; while [ "$#" -gt 0 ]; do case "$1" in --kind) kind="${2:-}"; shift 2;; --state) state="${2:-}"; shift 2;; --label) label="${2:-}"; shift 2;; --disposition) disposition="${2:-}"; shift 2;; *) fail "unknown node option: $1";; esac; done; [ -n "$kind" ] || fail '--kind is required'; case "$kind" in code|runtime_effect|boundary|external_system|concept_occurrence|explanation|hypothesis|timeline_event) ;; *) fail "invalid node kind: $kind";; esac; case "$state" in discovered|expanded) ;; *) fail "invalid node state: $state";; esac; case "$disposition" in primary|deferred) ;; *) fail "invalid node disposition: $disposition";; esac; id="$(new_id jn)"; append_record "$journey" node "$id" "$(jq -cn --arg id "$id" --arg kind "$kind" --arg state "$state" --arg label "$label" --arg disposition "$disposition" '{schema:"mana.learning.record/v1",record_type:"node",id:$id,kind:$kind,state:$state,label:$label,disposition:$disposition}')"; echo "$id" ;;
  add-edge)
    journey="${1:-}"; shift || true; require_journey "$journey"; from=""; to=""; kind=""; disposition=primary; while [ "$#" -gt 0 ]; do case "$1" in --from) from="${2:-}"; shift 2;; --to) to="${2:-}"; shift 2;; --kind) kind="${2:-}"; shift 2;; --disposition) disposition="${2:-}"; shift 2;; *) fail "unknown edge option: $1";; esac; done; [ -n "$from$to$kind" ] || fail '--from, --to, and --kind are required'; case "$kind" in CALLS|EXECUTES|DEPENDS_ON|RETURNS_TO|LOOP_BACK|EXPLAINS|EXEMPLIFIES|INTRODUCES_CONCEPT|DEEP_DIVE|MAY_EXIST_BECAUSE|SUPPORTED_BY|CONTRADICTED_BY|RELATED_TO) ;; *) fail "invalid edge kind: $kind";; esac; case "$disposition" in primary|deferred) ;; *) fail "invalid edge disposition: $disposition";; esac; require_id_kind "$journey" "$from" node; require_id_kind "$journey" "$to" node; id="$(new_id je)"; append_record "$journey" edge "$id" "$(jq -cn --arg id "$id" --arg from "$from" --arg to "$to" --arg kind "$kind" --arg disposition "$disposition" '{schema:"mana.learning.record/v1",record_type:"edge",id:$id,from:$from,to:$to,kind:$kind,disposition:$disposition}')"; echo "$id" ;;
  add-anchor)
    journey="${1:-}"; shift || true; require_journey "$journey"; node=""; revision=""; path=""; start=""; end=""; symbol=""; fingerprint=""; while [ "$#" -gt 0 ]; do case "$1" in --node) node="${2:-}"; shift 2;; --revision) revision="${2:-}"; shift 2;; --path) path="${2:-}"; shift 2;; --start-line) start="${2:-}"; shift 2;; --end-line) end="${2:-}"; shift 2;; --symbol) symbol="${2:-}"; shift 2;; --fingerprint) fingerprint="${2:-}"; shift 2;; *) fail "unknown anchor option: $1";; esac; done; [ -n "$node$revision$path$start$end" ] || fail 'anchor requires node, revision, path, start-line, end-line'; case "$start:$end" in *[!0-9:]*|:*) fail 'anchor lines must be positive integers';; esac; [ "$start" -ge 1 ] && [ "$end" -ge "$start" ] || fail 'anchor range is invalid'; require_id_kind "$journey" "$node" node; id="$(new_id anc)"; append_record "$journey" anchor "$id" "$(jq -cn --arg id "$id" --arg node "$node" --arg revision "$revision" --arg path "$path" --arg symbol "$symbol" --arg fingerprint "$fingerprint" --argjson start "$start" --argjson end "$end" '{schema:"mana.learning.record/v1",record_type:"anchor",id:$id,node_id:$node,revision:$revision,path:$path,symbol:$symbol,range:{start_line:$start,end_line:$end},structural_fingerprint:$fingerprint}')"; echo "$id" ;;
  add-evidence)
    journey="${1:-}"; shift || true; require_journey "$journey"; kind=""; anchor=""; summary=""; while [ "$#" -gt 0 ]; do case "$1" in --kind) kind="${2:-}"; shift 2;; --anchor) anchor="${2:-}"; shift 2;; --summary) summary="${2:-}"; shift 2;; *) fail "unknown evidence option: $1";; esac; done; [ -n "$kind" ] || fail '--kind is required'; case "$kind" in source_range|symbol|configuration|test|git_commit|git_diff|documentation|adr|runtime_semantic) ;; *) fail "invalid evidence kind: $kind";; esac; [ -z "$anchor" ] || require_id_kind "$journey" "$anchor" anchor; id="$(new_id ev)"; append_record "$journey" evidence "$id" "$(jq -cn --arg id "$id" --arg kind "$kind" --arg anchor "$anchor" --arg summary "$summary" '{schema:"mana.learning.record/v1",record_type:"evidence",id:$id,kind:$kind,summary:$summary} + (if $anchor == "" then {} else {anchor_id:$anchor} end)')"; echo "$id" ;;
  add-explanation)
    journey="${1:-}"; shift || true; require_journey "$journey"; subject=""; status=available; body=""; epistemic=unknown; evidence_lines=""; while [ "$#" -gt 0 ]; do case "$1" in --subject) subject="${2:-}"; shift 2;; --status) status="${2:-}"; shift 2;; --body) body="${2:-}"; shift 2;; --epistemic-status) epistemic="${2:-}"; shift 2;; --evidence) evidence_lines="${evidence_lines}${2:-}\n"; shift 2;; *) fail "unknown explanation option: $1";; esac; done; [ -n "$subject" ] || fail '--subject is required'; case "$status" in available|completed|failed) ;; *) fail "invalid explanation status: $status";; esac; case "$epistemic" in documented|strongly_supported|plausible|speculative|unknown) ;; *) fail "invalid explanation epistemic status: $epistemic";; esac; require_id_kind "$journey" "$subject" node; evidence="$(printf '%b' "$evidence_lines" | array_json)"; id="$(new_id exp)"; append_record "$journey" explanation "$id" "$(jq -cn --arg id "$id" --arg subject "$subject" --arg status "$status" --arg body "$body" --arg epistemic "$epistemic" --argjson evidence "$evidence" '{schema:"mana.learning.record/v1",record_type:"explanation",id:$id,subject_node_id:$subject,status:$status,body:$body,epistemic_status:$epistemic,evidence_ids:$evidence}')"; echo "$id" ;;
  add-enrichment)
    journey="${1:-}"; shift || true; require_journey "$journey"; request=""; subject=""; kind=""; status=""; reason=""; while [ "$#" -gt 0 ]; do case "$1" in --request-id) request="${2:-}"; shift 2;; --subject) subject="${2:-}"; shift 2;; --kind) kind="${2:-}"; shift 2;; --status) status="${2:-}"; shift 2;; --reason) reason="${2:-}"; shift 2;; *) fail "unknown enrichment option: $1";; esac; done; printf '%s' "$request" | grep -Eq '^exr_[a-f0-9]{24}$' || fail 'invalid enrichment request id'; [ -n "$subject$kind$status" ] || fail 'enrichment requires request-id, subject, kind, and status'; [ "$kind" = explanation ] || fail "invalid enrichment kind: $kind"; case "$status" in requested|completed|failed) ;; *) fail "invalid enrichment status: $status";; esac; require_id_kind "$journey" "$subject" node; id="$(new_id enr)"; append_record "$journey" enrichment "$id" "$(jq -cn --arg id "$id" --arg request "$request" --arg subject "$subject" --arg kind "$kind" --arg status "$status" --arg reason "$reason" '{schema:"mana.learning.record/v1",record_type:"enrichment",id:$id,request_id:$request,subject_node_id:$subject,kind:$kind,status:$status} + (if $reason == "" then {} else {reason:$reason} end)')"; echo "$id" ;;
  add-hypothesis)
    journey="${1:-}"; shift || true; require_journey "$journey"; subject=""; claim=""; confidence=plausible; supports_lines=""; contradicts_lines=""; while [ "$#" -gt 0 ]; do case "$1" in --subject) subject="${2:-}"; shift 2;; --claim) claim="${2:-}"; shift 2;; --confidence) confidence="${2:-}"; shift 2;; --supports) supports_lines="${supports_lines}${2:-}\n"; shift 2;; --contradicts) contradicts_lines="${contradicts_lines}${2:-}\n"; shift 2;; *) fail "unknown hypothesis option: $1";; esac; done; [ -n "$subject$claim" ] || fail '--subject and --claim are required'; case "$confidence" in documented|strongly_supported|plausible|speculative|unknown) ;; *) fail "invalid hypothesis confidence: $confidence";; esac; require_id_kind "$journey" "$subject" node; supports="$(printf '%b' "$supports_lines" | array_json)"; contradicts="$(printf '%b' "$contradicts_lines" | array_json)"; id="$(new_id hyp)"; append_record "$journey" hypothesis "$id" "$(jq -cn --arg id "$id" --arg subject "$subject" --arg claim "$claim" --arg confidence "$confidence" --argjson supports "$supports" --argjson contradicts "$contradicts" '{schema:"mana.learning.record/v1",record_type:"hypothesis",id:$id,subject_node_id:$subject,claim:$claim,confidence:$confidence,supports:$supports,contradicts:$contradicts}')"; echo "$id" ;;
  add-concept-occurrence)
    journey="${1:-}"; shift || true; require_journey "$journey"; concept=""; subject=""; relevance=primary; evidence_lines=""; while [ "$#" -gt 0 ]; do case "$1" in --concept-id) concept="${2:-}"; shift 2;; --subject) subject="${2:-}"; shift 2;; --relevance) relevance="${2:-}"; shift 2;; --evidence) evidence_lines="${evidence_lines}${2:-}\n"; shift 2;; *) fail "unknown concept occurrence option: $1";; esac; done; [ -n "$concept$subject" ] || fail '--concept-id and --subject are required'; concept_id_ok "$concept" || fail "invalid concept id: $concept"; case "$relevance" in primary|supporting|incidental) ;; *) fail "invalid concept relevance: $relevance";; esac; require_id_kind "$journey" "$subject" node; evidence="$(printf '%b' "$evidence_lines" | array_json)"; id="$(new_id occ)"; append_record "$journey" concept_occurrence "$id" "$(jq -cn --arg id "$id" --arg concept "$concept" --arg subject "$subject" --arg relevance "$relevance" --argjson evidence "$evidence" '{schema:"mana.learning.record/v1",record_type:"concept_occurrence",id:$id,concept_id:$concept,subject_node_id:$subject,relevance:$relevance,evidence_ids:$evidence}')"; echo "$id" ;;
  add-traversal)
    journey="${1:-}"; shift || true; require_journey "$journey"; kind=""; entry=""; nodes_lines=""; while [ "$#" -gt 0 ]; do case "$1" in --kind) kind="${2:-}"; shift 2;; --entry) entry="${2:-}"; shift 2;; --nodes) shift; while [ "$#" -gt 0 ] && [[ "$1" != --* ]]; do nodes_lines="${nodes_lines}$1\n"; shift; done;; *) fail "unknown traversal option: $1";; esac; done; [ -n "$kind$entry" ] || fail '--kind and --entry are required'; require_id_kind "$journey" "$entry" node; nodes="$(printf '%b' "$nodes_lines" | array_json)"; id="$(new_id trv)"; append_record "$journey" traversal "$id" "$(jq -cn --arg id "$id" --arg kind "$kind" --arg entry "$entry" --argjson nodes "$nodes" '{schema:"mana.learning.record/v1",record_type:"traversal",id:$id,kind:$kind,entry_node_id:$entry,node_ids:$nodes}')"; echo "$id" ;;
  add-cycle-region)
    journey="${1:-}"; shift || true; require_journey "$journey"; entry=""; kind=""; nodes_lines=""; edges_lines=""; while [ "$#" -gt 0 ]; do case "$1" in --entry) entry="${2:-}"; shift 2;; --kind) kind="${2:-}"; shift 2;; --nodes) shift; while [ "$#" -gt 0 ] && [[ "$1" != --* ]]; do nodes_lines="${nodes_lines}$1\n"; shift; done;; --back-edge) edges_lines="${edges_lines}${2:-}\n"; shift 2;; *) fail "unknown cycle region option: $1";; esac; done; [ -n "$entry$kind$nodes_lines$edges_lines" ] || fail 'cycle region requires entry, kind, nodes, and back-edge'; case "$kind" in retry|polling|event_loop|state_cycle|recursive|unknown) ;; *) fail "invalid cycle kind: $kind";; esac; require_id_kind "$journey" "$entry" node; nodes="$(printf '%b' "$nodes_lines" | array_json)"; edges="$(printf '%b' "$edges_lines" | array_json)"; id="$(new_id cyc)"; append_record "$journey" cycle_region "$id" "$(jq -cn --arg id "$id" --arg entry "$entry" --arg kind "$kind" --argjson nodes "$nodes" --argjson edges "$edges" '{schema:"mana.learning.record/v1",record_type:"cycle_region",id:$id,entry_node_id:$entry,kind:$kind,node_ids:$nodes,back_edge_ids:$edges}')"; echo "$id" ;;
  validate)
    journey="${1:-}"; [ "$#" -eq 1 ] || fail 'validate requires one journey id'; validate "$journey"; echo "Journey valid: $journey" ;;
  materialize)
    journey="${1:-}"; shift || true; [ -n "$journey" ] || fail 'materialize requires a journey id'; [ "${1:-}" = "--json" ] && shift; [ "$#" -eq 0 ] || fail 'unknown materialize option'; materialize "$journey" ;;
  *) fail "unknown or not-yet-supported journey command: $command" ;;
esac
